# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    - contextcheck
    - exhaustruct
    - exhaustivestruct
    - golint
    - gomnd
    - interfacer
    - ireturn # Too many false negatives.
    - lll
    - maligned
    - nlreturn # ignore "return with no blank line before"
    - nonamedreturns # unnecessary
    - nosnakecase
    - scopelint
    - varnamelen
    - wsl # ignore "declarations should never be cuddled"

linters-settings:
  varnamelen:
    ignore-decls:
      - l *Logger
      - l *rec.Logger
      - rw http.ResponseWriter
      - w http.ResponseWriter
      - r *http.Request
  wrapcheck:
    ignoreSigs:
      - func github.com/ginokent/cloudacme/pkg/errors.Errorf(format string, a ...interface{}) error
      - func (*github.com/rec-logger/rec.go.errorReturner).Err() error
      - func google.golang.org/grpc/status.Error(c google.golang.org/grpc/codes.Code, msg string) error

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - containedctx
        - cyclop
        - dupl
        - funlen
        - gochecknoglobals
        - gocognit
        - goconst
        - goerr113
        - maintidx
        - noctx
        - varnamelen
